# Generated by Django 3.2.13 on 2022-08-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='productname',
            new_name='servicename',
        ),
    ]
