# Generated by Django 3.2.13 on 2022-08-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_productname_services_servicename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='servicename',
            new_name='service_name',
        ),
    ]
