# Generated by Django 3.2.13 on 2022-08-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='price_id',
        ),
    ]
